rapido-linux/rapido

- cut_cephfs.sh
- cut_cephfs_fuse.sh
- cut_cifs.sh
- cut_dropbear.sh
- cut_fstests_cephfs.sh
- cut_fstests_local.sh
- cut_lio_local.sh
- cut_lio_rbd.sh
- cut_nvme_local.sh
- cut_nvme_rbd.sh
- cut_nvme_rdma.sh
- cut_qemu_rbd.sh
- cut_rbd.sh
- cut_tcmu_rbd_loop.sh
- cut_usb_rbd.sh
- rapido.conf.example
- runtime.vars
- tools/zram_setup.sh
This is built atop https://github.com/ddiss/rapido/pull/7 .
Common dracut parameters are moved into a runtime.vars function, which adds a --kmoddir argument if KERNEL_INSTALL_MOD_PATH is specified in rapido.conf .
> Dracut kmoddir

- runtime.vars
The --kmoddir expects the directory for the correct kernel version, not
the base directory where the modules will be installed.
Signed-off-by: Luis Henriques <lhenriques@suse.com>
> runtime.vars: fix dracut --kmoddir parameter

- runtime.vars
_rt_require_zram_params shouldn't check for the existence of the mount
point directories, as _zram_setup handles creation if missing. Creation
is needed for Ceph the vstart directories.
> tools/zram_setup.sh: fix mount-point dir creation

- rapido.conf.example
- runtime.vars
Until now, the CEPH_SRC rapido.conf parameter has required a path to
the "src" subdirectory of the Ceph source repository. This is counter
intuitive, given that all other X_SRC rapido.conf parameters correspond
repository root paths.
Drop the CEPH_SRC "src" subdirectory path requirement, and add temporary
support for translating CEPH_SRC="$ceph_repo/src" configurations into
into CEPH_SRC="$ceph_repo/src/../".
> runtime.vars: expect root repository path for CEPH_SRC

- cut_fstests_local.sh
rapido1:/fstests# grep -roh ' [^ ]*: command not found' results/ | sort -u
-v: command not found  <-- this is missing xfs_fsr
fgrep: command not found
pgrep: command not found
pvremove: command not found
quotacheck: command not found
quotaon: command not found
tar: command not found
vgremove: command not found
xfs_mdrestore: command not found
xfs_metadump: command not found
rapido1:/fstests# grep -rh '^[^ ]* not found$' results/  | sort -u
dbench not found
xfs_fsr not found
xfsdump not found
I skipped dbench for now because it would add a new dependency.
> cut_fstests_local.sh: Add more missing dependencies

- cut_fstests_cephfs.sh
- cut_fstests_cifs.sh
- cut_fstests_local.sh
I would like to add these extra 2 dependencies for running xfstests in rapido:
- fallocate is used in several generic tests in the test-suite
- libgdbm is required to compile (and run) tests that need src/dbtest.c
> Missing dependencies for xfstests

- nvme_rdma_autorun.sh
Use officially IANA assigned NVMe over Fabrics port, not 1023.
Signed-off-by: Johannes Thumshirn <jthumshirn@suse.de>
> nvme_rdma_autorun: use correct nvmf port

- cut_samba_cephfs.sh
- cut_samba_local.sh
- rapido.conf.example
- runtime.vars
- samba_cephfs_autorun.sh
- samba_local_autorun.sh
This patchset adds functionality to deploy a Samba server from source, and configure smb.conf with a share backed by CephFS or a locally provisioned zram device.
> Samba atop a local FS and CephFS

- readme.txt
- tools/br_setup.sh
- tools/br_teardown.sh
- tools/setup_br_ip_takeover.sh
tunctl is deprecated and will be remove from SLE15 base, so replace
all calls to tunctl with it's ip route2 equivalent.
Signed-off-by: Johannes Thumshirn <jthumshirn@suse.de>
> tools: use tuntap command from iproute2 instead of tunctl

- runtime.vars
--no-early-microcode ensures that an unnecessary "early microcode" CPIO
image isn't nested in Rapido initramfs images. On my laptop it
significantly speeds up image creation, and reduces size by ~3MB!:
(before)
> time ./cut_simple_example.sh
...
real    0m1.153s
user    0m0.927s
sys     0m0.401s
> l initrds/myinitrd
-rw------- 1 ddiss users 16229888 May 13 21:22 initrds/myinitrd
(after)
> time ./cut_simple_example.sh
...
real    0m1.060s
user    0m0.889s
sys     0m0.348s
> l initrds/myinitrd
-rw------- 1 ddiss users 12892672 May 13 21:24 initrds/myinitrd
> cut: call dracut with --no-early-microcode by default

- cut_openiscsi.sh
- openiscsi_autorun.sh
- rapido.conf.example
Generate an image with iscsid and iscsiadm from OPENISCSI_SRC. On boot,
connect to the target at INITIATOR_DISCOVERY_ADDR, issue a SendTargets
request and then login to any discovered targets.
> openiscsi: add cut and autorun

- autorun/fstests_cephfs.sh
- autorun/fstests_cifs.sh
- autorun/fstests_xfs.sh
- cut_fstests_btrfs.sh
- cut_fstests_cephfs.sh
- cut_fstests_cifs.sh
- cut_fstests_xfs.sh
The first commit was accidentally left out with https://github.com/rapido-linux/rapido/pull/59 . The second commit is something I came across while testing.
> fstests: fix cephfs, cifs and xfs

- cut_fstests_btrfs.sh
- cut_fstests_xfs.sh
shared/008,009 and 010 on btrfs and xfs need duperemove to run, provide it
to increase test coverage.
Signed-off-by: Johannes Thumshirn <jthumshirn@suse.de>
> cut_fstests: add "duperemove" dependency for btrfs and xfs

- autorun/cephfs_fuse.sh
- cut/cephfs_fuse.sh
- runtime.vars
I ran into a few issues with library dependencies following SES6 upgrade. This should make things a little more robust by relying on dracut's ldd dependency lookup behaviour.
> Fix cephfs_fuse

- autorun/samba_kernel_cephfs.sh
- cut/samba_kernel_cephfs.sh
This mostly matches samba_cephfs, but uses a kernel CephFS mountpoint
instead of libcephfs for filesystem I/O.
> samba_kernel_cephfs: kernel-backed Samba share runner

- cut/samba_cephfs.sh
- cut/samba_kernel_cephfs.sh
- cut/samba_local.sh
- rapido.conf.example
@rjfd hit https://github.com/rapido-linux/rapido/issues/44 while playing with Rapido, so I think it's time we add the virtio-rng-pci device to the default qemu parameter list.
> add virtio-rng-pci device and update samba dependencies

- rapido
I find myself mistyping './rapido vm' instead of './rapido boot' several
times a day, so just add a that command.
Signed-off-by: Johannes Thumshirn <jthumshirn@suse.de>
> rapido: add 'vm' alias for 'boot'

- vm.sh
On my system this speeds up time to /init for a network attached VM with
static IP from 3.143863s to 0.735700s - a >4X improvement.
kernel/*config files already include CONFIG_VIRTIO_NET=y, so no other
changes should be needed.
> vm: use qemu virtio network devices

- cut/ltp.sh
cat chown ip lsmod ping pkill sed tc
These are dependencies for LTP shell API and network tests
(some rarely used dependencies are omitted).
Signed-off-by: Petr Vorel <pvorel@suse.cz>
> LTP: add few more dependencies

- autorun/fstests_btrfs.sh
- autorun/fstests_cephfs.sh
- autorun/fstests_cifs.sh
- autorun/fstests_xfs.sh
- vm_autorun.env
This PR fixes issue #106 . Here's the commit changelog:
Several autorun scripts were creating /etc/hosts.  Add a common function
for doing that.  While there, create this file following the
recommendations from hosts(5), namely:
- use 127.0.0.1 for localhost
- use 127.0.1.1 for the FQDN
- add IPv6 entries
Signed-off-by: Luis Henriques <lhenriques@suse.com>
> vm_autorun.env: add function to create /etc/hosts file #106

- rapido.conf.example
- selftest/selftest.sh
- selftest/test/001
- selftest/test/002
- selftest/test/003
- vm.sh
selftest/selftest.sh runs a quick check to ensure that rapido can cut and boot the simple-example image.
> add self test coverage

- autorun/fstests_btrfs.sh
- autorun/fstests_xfs.sh
- rapido.conf.example
Make the size of the zram disks used for fstests configurable.
While we're at it, copy'n'paste the loop for setting the size from
fstests_btrfs.sh to fstests_xfs.sh as well to save some typing.
Signed-off-by: Johannes Thumshirn <jth@kernel.org>
> rapdio: make the size of the zram disks configurable

- cut/cephfs.sh
- cut/fstests_cephfs.sh
- cut/samba_kernel_cephfs.sh
It's not needed, and has a bunch of dependencies. ceph.conf and the
keyring can also be removed thanks to _rt_write_ceph_config().
> cut/cephfs: drop CEPH_MOUNT_BIN helper binary

- tools/zram_hot_add.sh
If called before the zram module is loaded, two zram devices appear.
This is due to the default num_devices=1 probe behaviour and
unconditional sysfs zram-control/hot_add use.
> tools/zram_hot_add: only add a single device

- cut/fstests_btrfs.sh
Since kernel v5.5 btrfs can use xxhash64 and sha256 as checksum hashes,
but we don't add the xxhash_generic driver to rapdio's initrd.
Add xxhash_generic to initrd, sha256 isn't needed as the rapido kernel
config has sha256 built in.
Signed-off-by: Johannes Thumshirn <johannes.thumshirn@wdc.com>
> rapdio: add xxhash_generic module to btrfs initrd

- runtime.vars
On my system this costs ~200ms every "cut" invocation. It's unnecessary,
as dracut invocation failures will be caught when we actually generate
the initramfs image.
> runtime.vars: drop dracut --list-modules sanity check

- rapido
- runtime.vars
Until now we've used "dracut --force" to overwrite any existing rapido
initramfs images. However, this means that existing xattrs on the
overwritten image (used to track rapido VM resources, etc.) are retained
for the new image.
To avoid retaining stale xattrs, remove any existing image before
invoking Dracut, which can now be done without the --force parameter.
Link: https://github.com/rapido-linux/rapido/issues/132
> rapido: remove existing image instead of using dracut --force

- autorun/zonefstests_scsi.sh
- cut/zonefstests_scsi.sh
Now that the kernel' scsi_debug driver can emulate zoned block devices, we
can add environment for zonefs tests over SCSI.
This way we also have regression tests for SCSI only callpaths zonefs will
take, like the emulation of the ZONE APPEND commands in the SCSI layer.
Signed-off-by: Johannes Thumshirn <johannes.thumshirn@wdc.com>
> rapdio: add environment for zonefs tests over SCSI

- autorun/tcmu_file_iscsi.sh
- cut/tcmu_file_iscsi.sh
Use the simple tcmu-runner file backend to expose a local file via
iSCSI.
> tcmu_file_iscsi: cut+autorun scripts for tcmu-runner iscsi

- rapido
Avoid flooding the screen with all testcase names and instead refer to
'rapido list'. Show usage help if an incorrect parameter is provided.
> rapido: minor cut usage help improvements

- autorun/unionmount_testsuite.sh
- cut/unionmount_testsuite.sh
- rapido.conf.example
This runs the upstream overlayfs test suite, as documented at
https://github.com/amir73il/overlayfs/wiki/Overlayfs-testing .
> unionmount_testsuite: add cut and autorun scripts

- autorun/fstests_btrfs_zoned.sh
- cut/fstests_btrfs_zoned.sh
Work in Progress!!!!
Add support for running fastest with btrfs on zoned null_blk devices.
Upstream btrfs has not yet merged zoned support (only staged in a separate branch) and user-space utilities are not update upstream either. But we have been using this cut script for about one year assisting our development of the patches.
> WIP: rapido: add fstests-btrfs-zoned cut script

- autorun/lio_local_alua_lba.sh
- cut/lio_local_alua_lba.sh
LIO carries support for Asymmetric Logical Unit Access, with path state
derived from a block address map. This commit adds coverage for this
somewhat hidden feature.
> lio_local_alua_lba: cut+autorun for lba based ALUA

- autorun/tcmu_file_iscsi.sh
- autorun/tcmu_rbd_loop.sh
Running tcmu-runner as a simple bash background job means that ctrl-c
entries at the shell prompt result in SIGINT delivery and subsequent
tcmu-runner shutdown.
setsid is provided via Dracut's base module, so should always be used
for proper process daemonization.
> autorun/tcmu: properly fork tcmu-runner daemon

- autorun/nvme_rdma.sh
- cut/nvme_rdma.sh
The 5.17-rcX kernel[1] has removed the module parameters, so
have to use the 'rdma' tool.
[1]: https://www.spinics.net/lists/linux-rdma/msg108004.html
Signed-off-by: Li Feng <fengli@smartx.com>
> rdma: use the rdma tool

- autorun/uring_btrfs.sh
- cut/uring_btrfs.sh
I'm seeing OOMs with liburing 2.1 on SLE15-SP4, so increase mem to 2G.
loopback is needed for the send_recvmsg test.
> uring_btrfs: increase memory and bring up loopback

- runtime.vars
- vm.sh
00-rapido-init.sh is currently installed as a Dracut emergency hook,
which gets invoked via:
```
[ -z "$root" ] && die "No or empty root= argument"
```
This means that we see a number of worrisome error messages before
rapido starts, e.g.
```
[    0.789194] Run /init as init process
[    0.860096] dracut: openSUSE Leap-15.3
[    0.886398] dracut: FATAL: No or empty root= argument
[    0.887587] dracut: Refusing to continue
[    0.891465] dracut Warning:
dracut Warning:
Rapido: starting /rapido_autorun/00-simple_example.sh
```
With this change, 00-rapido-init.sh is invoked as a dracut cmdline hook
which is executed before "root=" cmdline processing, resulting in less
noise on the console, e.g.:
```
[    0.706658] Run /init as init process
[    0.774859] dracut: openSUSE Leap-15.3
Rapido: …
```
> runtime: use dracut cmdline hook instead of emergency

- cut/fstests_cephfs.sh
rapido kernel/* configs have them built-in, so I hadn't noticed them
missing until now.
> cut/fstests_cephfs: add ceph and libceph kmods

- cut/fstests_btrfs.sh
The fstests "convert" group requires a bunch of ext user space
dependencies as well as the ext4 kernel module.
I've left fstests_btrfs_zoned as-is, as btrfs-convert probably doesn't
make sense there until ext4 is zone aware.
> cut/fstests_btrfs: add ext dependencies for convert

- tools/podman-import-initramfs.sh
Doesn't make much sense, given how much the rapido boot path expects
to modify the kernel, but can still be useful for poking around without
booting a VM.
> tools: add script to import initramfs as podman image

- autorun/uring_xfs.sh
- cut/uring_btrfs.sh
- cut/uring_xfs.sh
- rapido
- selftest/selftest.sh
```
The following changes since commit 24e3d1c868656561f3099c4d84253cbc35e60249:
Merge branch 'ublk' (2022-09-05 10:00:38 +0200)
https://github.com/ddiss/rapido selftest_and_uring
for you to fetch changes up to acc5d014f74633903d616798119f1d2ec9a2f1c9:
uring_xfs: add cut and autorun scripts (2022-09-24 00:03:17 +0200)
David Disseldorp (4):
rapido: drop command alias handling
selftest: minor cleanups
cut/uring_btrfs: add config.local and kernel tests
uring_xfs: add cut and autorun scripts
autorun/uring_xfs.sh | 37 +++++++++++++++++++++++++++++++++++++
cut/uring_btrfs.sh   | 20 +++++++++++++-------
cut/uring_xfs.sh     | 37 +++++++++++++++++++++++++++++++++++++
rapido               | 11 …
```
> Selftest and uring changes

- autorun/fstests_btrfs.sh
- autorun/fstests_exfat.sh
- autorun/fstests_ext4.sh
- autorun/fstests_xfs.sh
- cut/fstests_btrfs.sh
- cut/fstests_exfat.sh
- cut/fstests_ext4.sh
- cut/fstests_xfs.sh
This is required when using host-provided test/scratch block devices (feature added via https://github.com/rapido-linux/rapido/pull/170) on kernels built with CONFIG_VIRTIO_BLK=m. Rapido kconfigs in kernel/ specify CONFIG_VIRTIO_BLK=y, so this is mostly just for stock distro kernels.
cut/fstests_xfs.sh is updated to also pull in loop, scsi_debug and dm-log-writes kernel modules, which some tests desire.
Fixes: https://github.com/rapido-linux/rapido/issues/192
> fstests: add and load virtio_blk kernel module

- autorun/fstests_udf.sh
- cut/fstests_udf.sh
Very similar to other standalone fstests runners. Requires udftools (mkudffs) and udf kernel module dependencies. Uses a 4k block size inline with underlying zram block devices.
> fstests_udf: autorun and cut scripts

- rapido
- rapido.conf.example
- runtime.vars
- selftest/selftest.sh
- selftest/test/002
- selftest/test/003
- selftest/test/005
- tools/br_tap_setup.sh
- tools/br_tap_teardown.sh
- tools/net_conf_migrate.sh
- tools/podman-import-initramfs.sh
- vm.sh
This patchset attempt to remove all hardcoded `RAPIDO_DIR` paths for configuration and output files, making it much easier for independent CI jobs to run on the same host without the need to clone separate rapido repositories.
```
The following changes since commit 8571d3aa651f552f6eb735931397e3fd7e13e12a:
Merge branch 'udf_v2' (2023-01-25 00:04:03 +0100)
https://github.com/ddiss/rapido bug191_share_RAPIDO_DIR
for you to fetch changes up to 8a88b9d38598ade9c33889bc3312d9bda914f30a:
selftest/003: test QEMU_PID_DIR (2023-01-27 00:29:45 +0100)
David Disseldorp (9):
runtime.vars: drop hardcoded dracut tmpdir
Revert "rapido: remove existing image instead of using dracut --force" …
```
> Bug191: allow for sharing of RAPIDO_DIR between independent consumers

- cut/cifs.sh
- cut/fstests_cifs.sh
Needed for SMB3 connections. Also add the gcm kernel module dependency which was missing from cut/fstests_cifs.sh .
> cut/cifs: add cmac kernel module

- autorun/lib/samba.sh
- autorun/ocfs2.sh
- autorun/samba_cephfs.sh
- autorun/samba_kernel_cephfs.sh
- autorun/samba_local.sh
- cut/ocfs2.sh
- cut/samba_cephfs.sh
- cut/samba_kernel_cephfs.sh
- cut/samba_local.sh
- runtime.vars
```
The following changes since commit 535d0debee33887a4202905500fe7e322168f491:
Merge remote-tracking branch 'me-gh/cifs_kmods' (2023-02-14 21:39:48 +0100)
https://github.com/ddiss/rapido/ ocfs2_and_system_samba
for you to fetch changes up to 9f5fa7c2be4cb9cd7b9ba4347eff5a2aaf9c90b2:
ocfs2: add cut and autorun scripts (2023-02-17 17:07:28 +0100)
David Disseldorp (2):
samba: support use of locally installed samba binaries
ocfs2: add cut and autorun scripts
autorun/lib/samba.sh           | 34 ++++++++++++++++++++++++
autorun/ocfs2.sh               | 60 ++++++++++++++++++++++++++++++++++++++++++
autorun/samba_cephfs.sh        | 34 ++++++------------------
autorun/samba_kernel_cephfs.sh | …
```
> new OCFS2 runner and system samba support

- cut/cephfs_fuse.sh
- cut/ctdb_cephfs.sh
- cut/dropbear.sh
- cut/fcoe_local.sh
- cut/fstests_btrfs.sh
- cut/fstests_btrfs_zoned.sh
- cut/fstests_exfat.sh
- cut/lio_rbd.sh
- cut/lrbd.sh
- cut/nvme_local.sh
- cut/nvme_rbd.sh
- cut/nvme_rdma.sh
- cut/nvme_tcp_rbd.sh
- cut/qemu_rbd.sh
- cut/rbd.sh
- cut/rbd_nbd.sh
- cut/samba_cephfs.sh
- cut/samba_kernel_cephfs.sh
- cut/samba_local.sh
- cut/tcmu_rbd_loop.sh
- cut/usb_rbd.sh
- runtime.vars
Use variable references for `_rt_req_X` function return values instead of per-function magic global variables, as outlined in https://github.com/rapido-linux/rapido/issues/205 .
```
The following changes since commit 15c90a411fa4bc62c9a2a58f6f4e2c05a2d629e5:
Merge remote-tracking branch 'ddiss/keyctl_and_fstests_su' (2023-03-13 20:12:11 +0100)
https://github.com/ddiss/rapido.git drop_some_globals
for you to fetch changes up to 5d33cd5c7de69b2d9b87c5d9f5ef27d0f2518ca3:
cut: drop LIBS_INSTALL_LIST global (2023-03-18 00:33:49 +0100)
David Disseldorp (4):
cut/fstests_exfat: drop EXFAT_PROGS_BINS global
cut/fstests_btrfs: drop BTRFS_PROGS_BINS global
cut/samba: drop SAMBA_SRV_BINS global …
```
> Drop some globals

- autorun/fstests_ntfs3.sh
- autorun/ksmbd_btrfs.sh
- cut/fstests_ntfs3.sh
- cut/ksmbd_btrfs.sh
- rapido.conf.example
- runtime.vars
This makes use of the mkfs.ntfs binary from the ntfs-3g project.
> fstests_ntfs3 and ksmbd: add cut and autorun scripts

- cut/samba_btrfs.sh
- cut/samba_xfs.sh
As of dad4527, the local filesystem Samba runners provision one zram device of size FSTESTS_ZRAM_SIZE (or 1G if unset). Assign VM memory taking this into account, with 1G extra assigned for system memory.
Fixes: dad4527 ("samba-local: configure Btrfs backed shares")
> cut/samba: assign memory based on FSTESTS_ZRAM_SIZE

- cut/kselftest.sh
- dracut.conf.d/01-rapido-dracut.conf
Require ext2 and zram kernel modules as well as a few extra userspace binaries which are invoked by the tests scripts.
> cut/kselftest: add zram test dependencies

- rapido.conf.example
- readme.md
- runtime.vars
```
The following changes since commit 9c39d5aefbd9249d0f5965f20fbb58fafa47cb5c:
tools/br_tap_setup.sh: fix cleanup of rapido_tapdevs.X files (2023-07-27 14:57:53 +0200)
https://github.com/ddiss/rapido.git quick_start
for you to fetch changes up to 1903ee57dabd8e0dcf0d4a35cdddcc3385643c4a:
readme: add Quick Start section and rework Setup (2023-08-10 19:40:00 +0200)
David Disseldorp (2):
runtime: don't fail if rapido.conf is missing
readme: add Quick Start section and rework Setup
rapido.conf.example | 13 ++++++-------
readme.md           | 26 +++++++++++++++++---------
runtime.vars        |  9 +++++++--
3 files changed, 30 insertions(+), 18 deletions(-)
```
> Quick start

- autorun/lio_rbd_loop.sh
udevadm wait <bdev> is a new subcommand and not currently supported in e.g. SLE15-SP5. Replace it with a plain loop around udevadm settle.
> autorun/lio_rbd_loop: replace udevadm wait with settle loop

- autorun/ltp.sh
Kernel config in rapido is in nonstandard path, point the correct location via `KCONFIG_PATH` environment variable so that user does not have to do it manually.
Also move `KCONFIG_PATH` to `rapido.conf.example`, so that it does not have to be defined on both `autorun/ltp.sh` and `cut/ltp.sh`.
Fixes: db9be25 ("cut/ltp: Install kernel config when local kernel booted")
> autorun/ltp: Export `KCONFIG_PATH`

- cut/fstests_xfs.sh
- runtime.vars
xfs/122 uses the compiler to examine XFS type sizes. Use gcc -M in the cut script to obtain a recursive list of all dependencies for /usr/include/xfs/ headers.
> cut/fstests_xfs: include gcc and header files for xfs/122

- autorun/lib/fstests.sh
NVMe devices store their serial number in the 'device' sysfs directory, not the main block device sysfs directory.
> fstests: extract serial number for NVMe

- autorun/00-rapido-init.sh
- runtime.vars
- vm_autorun.env
Hanne's analysis:
vm_autorun.env is copied into the rapido root fs as /etc/profile,
and as such will be executed every time a login shell is invoked
(ie via 'su -' or 'sh -l'). As this script also serves as system
initialisation we need to make sure to run the initialisation only
once, and only export the environment variables for later invocations.
To avoid multiple invocations, we can use bash's explicit --rcfile parameter when starting the initial shell, and install vm_autorun.env in a path where it won't get invoked automatically (/rapido.rc).
To use bash with --rcfile, we also need to drop the explicit --login/-l parameter, which changes bash behaviour slightly:
- (unused) profile paths are different
- legacy fcntl(fd=[3->19], F_SETFD, FD_CLOEXEC) calls are skipped
I *think* we …
> autorun/init: start vm_autorun.env via bash --rcfile

- rapido
- selftest/test/002
- tools/bash_completion
The first minor batch of changes moving rapido towards distro package support, cherry picked from https://github.com/rapido-linux/rapido/pull/228 .
I've tacked on one extra selftests fix to handle upstream dracut output changes.
```
The following changes since commit c4e0cff00bfdaea03b960311266db5f59f7c5390:
usbip_host_stub: cut and autorun scripts (2024-11-25 13:59:18 +1100)
https://github.com/ddiss/rapido.git prelim_distro_pkg
for you to fetch changes up to b33a5a1f5e80105bc5151b3827266d1a2cd9b78d:
selftest/002: fix dracut-output needle (2024-11-26 15:52:33 +1100)
David Disseldorp (4):
runtime: use /etc/rapido/rapido.conf RAPIDO_CONF if present
tools/bash_completion: drop shebang …
```
> Preliminary distro packaging changes

- autorun/fstests_nfs.sh
- autorun/lib/nfs.sh
- autorun/nfs_client.sh
- autorun/nfsd_btrfs.sh
- cut/fstests_nfs.sh
- cut/nfs_client.sh
- cut/nfsd_btrfs.sh
```
The following changes since commit ec3ad7557ed657007be05a12abacf83801516873:
runtime: fix network dependency check (2024-12-03 10:29:17 +1100)
https://github.com/ddiss/rapido.git nfs_fix_mount
for you to fetch changes up to 5af4b4be79cc3e585cd730e288285aa6ea2972d6:
autorun/lib/nfs: setup /etc/protocols to fix mount (2024-12-03 16:15:09 +1100)
David Disseldorp (2):
autorun/nfs: split out /etc/ config helper
autorun/lib/nfs: setup /etc/protocols to fix mount
autorun/fstests_nfs.sh | 36 +-----------------------------------
autorun/lib/nfs.sh     | 49 +++++++++++++++++++++++++++++++++++++++++++++++++
autorun/nfs_client.sh  | 36 +-----------------------------------
autorun/nfsd_btrfs.sh …
```
> nfs: fix client mounts and remove duplicate /etc/ config provisioning

- autorun/lklfuse_udev_usb.sh
- cut/lklfuse_udev_usb.sh
- rapido.conf.example
Install lklfuse and the corresponding udev/systemd logic to mount USB attached block devices from an unprivileged user-space process. A new LKL_SRC rapido.conf parameter is added for obtaining lkl dependencies.
> lklfuse_udev_usb: cut and autorun scripts

- autorun/initramfs_verify.sh
- autorun/lkl_tests.sh
- cut/initramfs_verify.sh
- cut/lkl_tests.sh
- cut/lklfuse_udev_usb.sh
v2: I've tacked on one extra initramfs-verify change
```
The following changes since commit c9337a55e90e60716f2d27613f6a078326f956ac:
Merge branch 'lklfuse' (2025-02-27 23:39:38 +1100)
https://github.com/ddiss/rapido.git lkl_tests
for you to fetch changes up to 1c4ed65ea6f88a5a1623b2645c41084f8134eeac:
initramfs_verify: compressed cpio after uncompressed (2025-03-29 00:45:22 +1100)
David Disseldorp (3):
cut/lklfuse_udev_usb: use install-optional for file magic.mgc
lkl_tests: cut and autorun
initramfs_verify: compressed cpio after uncompressed
autorun/initramfs_verify.sh |  3 ++
autorun/lkl_tests.sh        | 23 +++++++++++++
cut/initramfs_verify.sh     |  7 ++++
cut/lkl_tests.sh …
```
> LKL testing improvements

- runtime.vars
When only number of CPUs is specified, qemu chooses some topology. The issue is when running a kernel without ACPI support that cannot obtain the topology from ACPI data, it falls back to parsing legacy mptable and this format cannot convey more that 1 core per socket (qemu's BIOS rejects changing this [1]).
The implicit topology used to work with qemu <6.2 which prefered sockets over cores but it doesn't in later versions which put cores above sockets.
Therefore synthesize the coarsest topology in rapido's resource helper, so that non-ACPI kernels can detect right number of vCPUs.
[1] https://www.mail-archive.com/seabios@seabios.org/msg13239.html
> runtime: Specify vCPUs with explicit (socket) topology

- autorun/autofs_direct_cifs.sh
- autorun/autofs_direct_nfs.sh
- autorun/autofs_indirect_cifs.sh
- cut/autofs_direct_cifs.sh
- cut/autofs_direct_nfs.sh
- cut/autofs_indirect_cifs.sh
- rapido.conf.example
- runtime.vars
I've had these laying around for some time and had to dig them up again for a recent bug report.
```
The following changes since commit 8f62848e0a59f276430a153ddb5fec598cb05cc5:
Merge remote-tracking branch 'lkl_mmu' into master (2025-06-11 21:42:32 +1000)
https://github.com/ddiss/rapido.git autofs_filemaps
for you to fetch changes up to 4732c43fd166a1fac81d4395ea8337d31937bc15:
autofs_direct_nfs: new cut and autorun scripts (2025-07-21 09:08:54 +1000)
David Disseldorp (3):
autofs_indirect_cifs: local autofs map for SMB shares
autofs_direct_cifs: local direct autofs map for SMB shares
autofs_direct_nfs: new cut and autorun scripts
autorun/autofs_direct_cifs.sh   | 47 …
```
> A few autofs runners

- autorun/00-rapido-init.sh
- vm_autorun.env
There are cuts that setup the environment with fully-fledged PID1 as systemd. Pulling the plug in such cases may or may not work depending on the ACPI support in the kernel/hypervisor.
The system may be left in not well-defined state when _only_ sysrq is invoked where most of the userspace is left running.
Fix this by detecting which kind of setup we're in and ask PID1 to nicely shut down (via signals to avoid dependency on systemctl).
---
The implementation is little rough but it prevents me ending up with borked VM.
> vm_autorun.env: Provide shutdown handler with systemd

- autorun/fstests_ovl_xfs.sh
- cut/fstests_ovl_xfs.sh
Add xfs-backed-overlayfs runner for fstests. fstests can be used as a harness for the unionmount testsuite, but we already have unionmount_testsuite, so omit the testsuite from the image for now.
> fstests_ovl_xfs: cut and autorun scripts
